### ISSUE TITLE
crash - if (((ThermoRawFile)myMsDataFile).monoisotopicPrecursorSelectionEnabled)

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/mzCal#29]
not sure if this is related to using two dictionaries. mzid files had unimod and psi-mod listed, which seems fine.

            else
            {
                myMsDataFile = new ThermoRawFile(origDataFile);
                myMsDataFile.Open();
                if (((ThermoRawFile)myMsDataFile).monoisotopicPrecursorSelectionEnabled)
                    deconvolute = false;
            }

followed by

           }
            else
                throw new Exception("Not familiar with modification dictionary " + dictionary);

**Comment by stefanks** [comment]
resolved in metamorpheus
